// Generated by CoffeeScript 1.3.3
"use strict"

var create, extend, factory, luma, right;

require(__dirname + '/node_modules/sinful/sinful.js')

luma = require('luma')

factory = luma.factory

create = luma.create

extend = luma.extend

right = factory({
  number: require('nmbr'),
  parser: require('prsr'),
  what: function(input) {
    var text
    text = this.parser(input)
    return text[0]
  },
  init: function(input) {
    return this.what(input)
  }
})

module.exports = right
